# Generated by Django 2.0.5 on 2018-05-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField()),
                ('modified_time', models.DateTimeField()),
                ('content', models.TextField()),
                ('title', models.TextField()),
                ('post_url', models.TextField()),
            ],
        ),
    ]
